---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      ignore: .virtualenv
platforms:
  - name: worker_bionic
    image: solita/ubuntu-systemd:bionic
    command: /sbin/init
    ulimits:
      - nofile:262144:262144
    privileged: true
    memory_reservation: 2048m
provisioner:
  name: ansible
  config_options:
    defaults:
      hash_behaviour: merge
  playbooks:
    docker:
      create: ../default/create.yml
      destroy: ../default/destroy.yml
      prepare: ../default/prepare.yml
  env:
    ANSIBLE_ROLES_PATH: ../../roles
  lint:
    name: ansible-lint
    enabled: true
scenario:
  name: worker
  test_sequence:
    - lint
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
