
- hosts: wazuh-manager
  roles:
      - { role: ansible-wazuh-manager }
      - { role: ansible-role-elasticsearch, elasticsearch_network_host: 'localhost' }
      - { role: ansible-role-logstash, logstash_input_beats: true, elasticsearch_network_host: 'localhost' }
      - { role: ansible-role-kibana, elasticsearch_network_host: 'localhost' }
