---

- name: Deploy Wazuh agent(s)
  hosts: agents
  strategy: free
  vars:
    wazuh_manager_address: "<Your Wazuh Manager IP>"
  roles:
    - role: package-urls
  tasks:
    - name: Include wazuh-agent role for Linux/MacOS hosts
      when: ansible_facts.system == "Linux" or ansible_facts.system == "Darwin"
      become: true
      become_user: root
      block:
        - name: Include Wazuh agent role for Linux
          ansible.builtin.include_role:
            name: wazuh-agent

    - name: Include wazuh-agent role for Windows hosts
      when: ansible_facts.os_family == "Windows"
      ansible.builtin.include_role:
        name: wazuh-agent
