---
dependency:
  name: shell
  command: ansible-galaxy collection install -r ../../../../../requirements.yml --force && pip install --upgrade -r ../../../../pip-requirements.txt

scenario:
  name: default
  test_sequence:
    - dependency
    - lint
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - destroy

driver:
  name: delegated
  tf_base_dir: ${MOLECULE_SCENARIO_DIRECTORY}/../../../../../../collections/ansible_collections/joom/common/molecule/resources/terraform
  tf_ec2_stack: ec2_terraform
  tf_vault_stack: vault_terraform
  tf_workspace: molecule-${BUILD_NUMBER:-$USER}-wazuh-default

# lint: |
#         yamllint .
#         ansible-lint
#         flake8
platforms:
  - name: molecule-${BUILD_NUMBER:-$USER}-wazuh-default-0.joom.d
    groups:
      - wazuh-master
  - name: molecule-${BUILD_NUMBER:-$USER}-wazuh-default-1.joom.d
    groups:
      - wazuh-worker
  - name: molecule-${BUILD_NUMBER:-$USER}-wazuh-default-2.joom.d
    groups:
      - wazuh-agent
  - name: molecule-${BUILD_NUMBER:-$USER}-wazuh-default-m6g-medium-0.joom.d
    groups:
      - wazuh-agent
  - name: molecule-${BUILD_NUMBER:-$USER}-wazuh-default-centos-0.joom.d
    groups:
      - wazuh-agent

provisioner:
  name: ansible
  config_options:
    defaults:
      verbosity: 2
  inventory:
    links:
      group_vars: ../inventory/group_vars/
  playbooks:
    prepare: ../resources/prepare.yml
    create: ../../../../../../collections/ansible_collections/joom/common/molecule/resources/create.yml
    destroy: ../../../../../../collections/ansible_collections/joom/common/molecule/resources/destroy.yml

verifier:
  name: ansible
