---
- name: RedHat/CentOS/Fedora | Install Filebeats repo
  yum_repository:
    name: elastic_repo
    description: Elastic repository for 6.x packages
    baseurl: https://artifacts.elastic.co/packages/6.x/yum
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    gpgcheck: yes
