---
galaxy_info:
  author: Wazuh
  description: Installing and maintaining Elasticsearch server.
  company: wazuh.com
  license: license (GPLv3)
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - all
  - name: Fedora
    versions:
    - all
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  galaxy_tags:
    - web
    - system
    - monitoring
