---
- name: Ensure Logstash SSL key pair directory exists.
  file:
    path: "{{ logstash_ssl_dir }}"
    state: directory
  when: logstash_ssl
  tags: configure

- name: Copy SSL key and cert for logstash.
  copy:
    src: "{{ item }}"
    dest: "{{ logstash_ssl_dir }}/{{ item | basename }}"
    mode: 0644
  with_items:
    - "{{ logstash_ssl_key_file }}"
    - "{{ logstash_ssl_certificate_file }}"
  when: logstash_ssl
  tags: configure

- name: Logstash configuration
  template:
    src: 01-wazuh.conf.j2
    dest: /etc/logstash/conf.d/01-wazuh.conf
    owner: root
    group: root
  notify: restart logstash
  tags: configure
