---
- when: logstash_install_java
  block:
    - name: RedHat/CentOS/Fedora | Install OpenJDK 1.8
      yum: name=java-1.8.0-openjdk state=present
      register: oracle_java_task_rpm_installed
      tags: install

- name: RedHat/CentOS/Fedora | Install Logstash repo
  yum_repository:
    name: elastic_repo
    description: Elastic repository for 6.x packages
    baseurl: https://artifacts.elastic.co/packages/6.x/yum
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    gpgcheck: true

- name: RedHat/CentOS/Fedora | Install Logstash
  package: name=logstash-{{ elastic_stack_version }} state=present
  when: not logstash_install_java or oracle_java_task_rpm_installed is defined
  tags: install

- name: RedHat/CentOS/Fedora | Checking if wazuh-manager is installed
  command: rpm -q wazuh-manager
  register: wazuh_manager_check_rpm
  when: logstash_input_beats == false
  args:
    warn: false

- name: RedHat/CentOS/Fedora | Add user logstash to group ossec
  user:
    name: logstash
    groups: ossec
    append: true
  when:
    - logstash_input_beats == false
    - wazuh_manager_check_rpm.rc == 0

- name: Amazon Linux change startup group
  shell: sed -i 's/.*LS_GROUP=logstash.*/LS_GROUP=ossec/' /etc/logstash/startup.options
  when:
    - logstash_input_beats == false
    - wazuh_manager_check_rpm.rc == 0
    - ansible_distribution == "Amazon" and ansible_distribution_major_version == "NA"
