---

- hosts: aio
  become: yes
  roles:
    - role: ../../roles/package-urls
      source: 'custom'
    - role: ../../roles/wazuh-indexer
    - role: ../../roles/wazuh-server
    - role: ../../roles/wazuh-dashboard
  vars:
    single_node: true
