---
- block:

  - include_vars: debian.yml 
  - name: Add apt repository signing key
    apt_key:
      url: "{{ package_repos.apt.opendistro.gpg }}"
      state: present

  - name: Debian systems | Add OpenDistro repo
    apt_repository:
      repo: "{{ package_repos.apt.opendistro.baseurl }}"
      state: present
      update_cache: yes

  - name: Install Kibana
    apt:
      name: "opendistroforelasticsearch-kibana={{ kibana_opendistro_version }}"
      state: present
    register: install

  tags:
    - install 