---
galaxy_info:
  author: Wazuh
  description: Installing, deploying and configuring Wazuh Agent.
  company: wazuh.com
  license: license (GPLv3)
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - monitoring
dependencies: []
