---
- name: Debian/Ubuntu | Install apt-transport-https, ca-certificates and acl
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - acl
    state: present
  register: filebeat_ca_packages_install
  until: filebeat_ca_packages_install is succeeded

- name: Debian/Ubuntu | Add Elasticsearch apt key.
  apt_key:
    url: "{{ filebeatrepo.gpg }}"
    id: "{{ filebeatrepo.key_id }}"
    state: present

- name: Debian/Ubuntu | Add Filebeat-oss repository.
  apt_repository:
    repo: "{{ filebeatrepo.apt }}"
    state: present
    update_cache: true
  changed_when: false
