---

- block:
  - name: Cert-gen [Local action] | Check if certificates already exists
    stat:
      path: "{{ local_certs_path }}"
    register: certificates_folder

  - name: Cert-gen [Local action] | Check if current host (control node) is macOS
    set_fact:
      macos_localhost: "{{ ansible_os_family == 'Darwin' }}"

  run_once: true
  delegate_to: localhost
  become: no

- block:
  - name: Cert-gen [Local action] | Create local temporary directory for certificates generation
    file:
      path: "{{ local_certs_path }}"
      mode: 0755
      state: directory

  - name: Cert-gen [Local action] | Certificate generation for non-macOS hosts
    block:
      - name: Cert-gen [Local action] | Check that the generation tool exists
        stat:
          path: "{{ local_certs_path }}/wazuh-certs-tool.sh"
        register: tool_package

      - name: Cert-gen [Local action] | Download certificates generation tool
        get_url:
          url: "{{ certs_gen_tool_url }}"
          dest: "{{ local_certs_path }}/wazuh-certs-tool.sh"
        when: not tool_package.stat.exists

      - name: Cert-gen [Local action] | Prepare the certificates generation template file
        template:
          src: "templates/config.yml.j2"
          dest: "{{ local_certs_path }}/config.yml"
          mode: 0644
        register: tlsconfig_template

      - name: Cert-gen [Local action] | Generate the node & admin certificates in local
        command: >-
          bash {{ local_certs_path }}/wazuh-certs-tool.sh -A
    when: not macos_localhost

  - name: Cert-gen [Local action] | Certificate generation for macOS hosts
    block:
      - name: Cert-gen [Local action] | Check for Docker installation on macOS
        command: docker --version
        register: docker_check
        ignore_errors: yes

      - name: Cert-gen [Local action] | Fail if Docker is not installed
        fail:
          msg: "Docker is not installed on this host."
        when: (docker_check.rc | default(1)) != 0

      - name: Cert-gen [Local action] | Run Docker container on macOS
        community.docker.docker_container:
          name: wazuh-cert-tool
          image: "{{ wazuh_certs_tool_docker }}"
          state: started
          auto_remove: true
          volumes:
            - "{{ local_certs_path }}/config.yml:/config/certs.yml"
            - "{{ local_certs_path }}/wazuh-certificates/:/certificates/"

      - name: Cert-gen [Local action] | Remove Docker image after execution
        community.docker.docker_image:
          name: "{{ wazuh_certs_tool_docker }}"
          state: absent
          force_absent: yes
    when: macos_localhost

  run_once: true
  delegate_to: localhost
  become: no
  when:
    - not certificates_folder.stat.exists

- name: Copy the node & admin certificates to Wazuh indexer cluster
  copy:
    src: "{{ local_certs_path }}/wazuh-certificates/{{ item }}"
    dest: "/etc/wazuh-indexer/certs/"
    owner: wazuh-indexer
    group: wazuh-indexer
    mode: 0400
  with_items:
    - root-ca.pem
    - root-ca.key
    - "{{ indexer_node_name }}-key.pem"
    - "{{ indexer_node_name }}.pem"
    - admin-key.pem
    - admin.pem
