---

- name: Install Wazuh indexer dependencies
  apt:
    name:
      - 'unzip'
      - 'wget'
      - 'curl'
      - 'apt-transport-https'
      - 'software-properties-common'
    state: present

- name: Linux Debian (AMD64) | Download wazuh-indexer package
  get_url:
    url: "{{ wazuh_indexer_url_amd64_deb }}"
    dest: "{{ wazuh_indexer_package_download_path }}/{{ wazuh_indexer_package_name }}"
  when:
    - ansible_architecture == "x86_64"

- name: Linux Debian (ARM64) | Download wazuh-indexer package
  get_url:
    url: "{{ wazuh_indexer_url_arm64_deb }}"
    dest: "{{ wazuh_indexer_package_download_path }}/{{ wazuh_indexer_package_name }}"
  when:
    - ansible_architecture == "aarch64"
