---

- name: Amazon Linux | Configure system settings
  block:
    - name: Install Amazon extras in Amazon Linux 2
      yum:
        name: amazon-linux-extras
        state: present
      when:
        - ansible_distribution == 'Amazon'
        - ansible_distribution_major_version == '2'

    - name: Configure vm.max_map_count
      lineinfile:
        line: "vm.max_map_count=262144"
        dest: "/etc/sysctl.conf"
        insertafter: EOF
        create: true
      become: yes

    - name: Update vm.max_map_count
      shell: sysctl -p
      become: yes

  when:
    - ansible_distribution == 'Amazon'

- name: RedHat/CentOS/Fedora | Install Indexer dependencies
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - coreutils
    - wget
    - unzip

- name: Linux CentOS/RedHat (x86_64) | Download wazuh-indexer package
  get_url:
    url: "{{ wazuh_indexer_url_amd64_rpm }}"
    dest: "{{ wazuh_indexer_package_download_path }}/{{ wazuh_indexer_package_name }}"
  when:
    - ansible_architecture == "x86_64"

- name: Linux CentOS/RedHat (aarch64) | Download wazuh-indexer package
  get_url:
    url: "{{ wazuh_indexer_url_arm64_rpm }}"
    dest: "{{ wazuh_indexer_package_download_path }}/{{ wazuh_indexer_package_name }}"
  when:
    - ansible_architecture == "aarch64"
