---

single_node: false
indexer_node_name: node-1
indexer_network_host: '0.0.0.0'
instances:
  node-1:
    name: node-1
    ip: '0.0.0.0'
    role: indexer

generate_certs: true
local_configs_path: "{{ playbook_dir }}/indexer-config"

wazuh_indexer_package_download_path: "/tmp/wazuh-indexer"
wazuh_indexer_package_name: "wazuh-indexer-package"
