indexer_version: 5.0.0

single_node: false
indexer_node_name: node-1

generate_certs: true
certs_gen_tool_version: "5.0"
local_certs_path: "{{ playbook_dir }}/indexer/certificates"
certs_gen_tool_url: "https://packages-dev.wazuh.com/{{ certs_gen_tool_version }}/wazuh-certs-tool.sh"
wazuh_certs_tool_docker: "wazuh/wazuh-cert-tool:{{ indexer_version }}" # for MacOS

wazuh_indexer_url_amd64_deb: ""
wazuh_indexer_url_arm64_deb: ""
wazuh_indexer_url_amd64_rpm: ""
wazuh_indexer_url_arm64_rpm: ""

wazuh_indexer_package_download_path: "/tmp/wazuh-indexer"
wazuh_indexer_package_name: "wazuh-indexer-package"
