---
name: AIO-Single-Instance-Test
on:
  workflow_dispatch:
    inputs:
      AUTOMATION_REFERENCE:
        description: 'Branch or tag of the wazuh-automation repository'
        required: true
        default: 'main'
      OS_LIST:
        description: 'Operating Systems (comma-separated string list)'
        required: true
        default: '["CentOS_8", "AmazonLinux_2", "Ubuntu_22", "RHEL8"]'
        type: string
      COMMIT_LIST:
        description: 'Wazuh components revisions (comma-separated string list) ["indexer", "server", "dashboard", "agent"]'
        required: true
        default: '["latest", "latest", "latest", "latest"]'
        type: string
      ENVIRONMENT:
        description: 'Environment to run the playbook'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - prerelease
          - production
      VERBOSITY:
        description: 'Verbosity level on playbooks execution'
        required: true
        default: 'normal'
        type: choice
        options:
          - normal
          - -v
          - -vv
          - -vvv
          - -vvvv
  pull_request:
  release:
env:
  COMPOSITE_NAME: "linux-SUBNAME-amd64"
  ALLOCATOR_PATH: "/tmp/allocator_instance"
  DEPLOY_TEMP_DIR: "/tmp/wazuh-ansible"
  ARTIFACTS_URLS_FILE_TEMP: "artifacts_urls.yml"
  PRESIGNED_OUTPUT_FILE: "artifacts_urls_presigned.yml"
permissions:
  id-token: write # JWT
  contents: read # actions/checkout
jobs:
  setup-runner:
    name: Setup runner
    runs-on: ubuntu-latest
    steps:
      - name: Display workflow inputs
        run: echo "${{ toJson(inputs) }}"
      - name: Compute outputs
        id: compute-outputs
        run: |
          # Set OS_LIST
          if [[ "${{ inputs.OS_LIST }}" != "null" && "${{ inputs.OS_LIST }}" != "" ]]; then
            OS_LIST='${{ inputs.OS_LIST }}'
          else
            OS_LIST='["CentOS_8", "AmazonLinux_2", "Ubuntu_22", "RHEL8"]'
          fi
          echo "OS_LIST=$OS_LIST" >> $GITHUB_OUTPUT

          # Set WAZUH_TEMPLATE_BRANCH
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            WAZUH_TEMPLATE_BRANCH=${{ github.base_ref }}
          else
            WAZUH_TEMPLATE_BRANCH=${{ github.ref }}
            # Remove refs/heads/ or refs/tags/ from the branch name
            WAZUH_TEMPLATE_BRANCH=${WAZUH_TEMPLATE_BRANCH#refs/heads/}
            WAZUH_TEMPLATE_BRANCH=${WAZUH_TEMPLATE_BRANCH#refs/tags/}
          fi
          echo "WAZUH_TEMPLATE_BRANCH=$WAZUH_TEMPLATE_BRANCH" >> $GITHUB_OUTPUT

          # Set VERBOSITY
          if [[ "${{ inputs.VERBOSITY }}" != "null" && "${{ inputs.VERBOSITY }}" != "normal" ]]; then
            VERBOSITY="${{ inputs.VERBOSITY }}"
          else
            VERBOSITY=''
          fi
          echo "VERBOSITY=$VERBOSITY" >> $GITHUB_OUTPUT
          echo "Verbosity level: $VERBOSITY"

          # Set ENVIRONMENT
          if [[ "${{ inputs.ENVIRONMENT }}" != "null" && "${{ inputs.ENVIRONMENT }}" != "" ]]; then
            ENVIRONMENT="${{ inputs.ENVIRONMENT }}"
          else
            ENVIRONMENT='development'
          fi
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_OUTPUT
          echo "Environment: $ENVIRONMENT"

          # Set REVISIONS
          if [[ "${{ inputs.COMMIT_LIST }}" != "null" && "${{ inputs.COMMIT_LIST }}" != "" ]]; then
            COMMIT_LIST='${{ inputs.COMMIT_LIST }}'
          else
            COMMIT_LIST='["latest", "latest", "latest", "latest"]'
          fi
          echo "COMMIT_LIST=$COMMIT_LIST" >> $GITHUB_OUTPUT
          echo "Revision list (indexer, server, dashboard, agent): $COMMIT_LIST"
    outputs:
      OS_LIST: ${{ steps.compute-outputs.outputs.OS_LIST }}
      WAZUH_TEMPLATE_BRANCH: ${{ steps.compute-outputs.outputs.WAZUH_TEMPLATE_BRANCH }}
      VERBOSITY: ${{ steps.compute-outputs.outputs.VERBOSITY }}
      ENVIRONMENT: ${{ steps.compute-outputs.outputs.ENVIRONMENT }}
      COMMIT_LIST: ${{ steps.compute-outputs.outputs.COMMIT_LIST }}
  package-urls:
    name: Generate package URLs (if applicable)
    runs-on: ubuntu-latest
    needs: setup-runner
    if: ${{ needs.setup-runner.outputs.ENVIRONMENT == 'development' }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: us-east-1
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: wazuh-ansible/
      - name: Download S3 package URIs file (if applicable)
        run: |
          # Generate a pre-signed URL for the S3 file
          S3_BUCKET="xdrsiem-devops-wazuh-artifacts"
          S3_KEY="deployment/5.0/artifacts_urls.yml"
          EXPIRATION=3600 # 1 hour
          PRESIGNED_URL=$(aws s3 presign s3://$S3_BUCKET/$S3_KEY --expires-in $EXPIRATION --region us-west-1)
          echo "Generated pre-signed URL: $PRESIGNED_URL"

          # Create a temporary directory to store files
          mkdir -p "${{ env.DEPLOY_TEMP_DIR }}"

          # Download the file using the pre-signed URL
          curl -o $DEPLOY_TEMP_DIR/$ARTIFACTS_URLS_FILE_TEMP "$PRESIGNED_URL"

          # Verify the file was downloaded
          if [ -f $DEPLOY_TEMP_DIR/$ARTIFACTS_URLS_FILE_TEMP ]; then
            echo "S3 package URIs file downloaded successfully."
          else
            echo "Failed to download S3 package URIs file." >&2
            exit 1
          fi
      - name: Generate the variables file (signing each package URI)
        run: |
          # Define necessary variables
          VERSION_FILE="wazuh-ansible/VERSION.json"
          WAZUH_VERSION=$(jq -r '.version' "$VERSION_FILE")
          WAZUH_MAJOR=$(echo "$WAZUH_VERSION" | cut -d '.' -f 1)
          COMMIT_LIST='${{ needs.setup-runner.outputs.COMMIT_LIST }}'
          OUTPUT_FILE="/tmp/artifacts_urls_processed.yml"

          # Extract revisions using jq
          INDEXER_COMMIT=$(echo "$COMMIT_LIST" | jq -r '.[0]')
          SERVER_COMMIT=$(echo "$COMMIT_LIST" | jq -r '.[1]')
          DASHBOARD_COMMIT=$(echo "$COMMIT_LIST" | jq -r '.[2]')
          AGENT_COMMIT=$(echo "$COMMIT_LIST" | jq -r '.[3]')

          # Verify if the input file exists
          if [ ! -f "$DEPLOY_TEMP_DIR/$ARTIFACTS_URLS_FILE_TEMP" ]; then
            echo "The input file $DEPLOY_TEMP_DIR/$ARTIFACTS_URLS_FILE_TEMP does not exist." >&2
            exit 1
          fi

          # Process the file line by line (replacing ocurrences)
          while IFS= read -r line || [ -n "$line" ]; do
            # Skip empty lines and comments
            if [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]]; then
              echo "$line" >> "$OUTPUT_FILE"
              continue
            fi

            # Replace MAJOR with the major version
            line=${line//MAJOR/$WAZUH_MAJOR}

            # Replace WAZUH_VERSION with the full version
            line=${line//WAZUH_VERSION/$WAZUH_VERSION}

            # Handle the different component revisions based on the URL pattern
            if [[ "$line" == *"wazuh_indexer_url"* ]]; then
              line=${line//latest/$INDEXER_COMMIT}
            elif [[ "$line" == *"wazuh_server_url"* ]]; then
              line=${line//latest/$SERVER_COMMIT}
            elif [[ "$line" == *"wazuh_dashboard_url"* ]]; then
              line=${line//latest/$DASHBOARD_COMMIT}
            elif [[ "$line" == *"wazuh_agent_url"* ]]; then
              line=${line//latest/$AGENT_COMMIT}
            fi

            # Append the processed line to the output file
            echo "$line" >> "$OUTPUT_FILE"
          done < "$DEPLOY_TEMP_DIR/$ARTIFACTS_URLS_FILE_TEMP"

          # Verify the output file
          if [ -f "$OUTPUT_FILE" ]; then
            echo "The downloaded file artifacts_urls.yml was successfully processed at $OUTPUT_FILE."
          else
            echo "Failed to create processed artifacts_urls.yml file." >&2
            exit 1
          fi

          # Generate the presigned URLs for each package
          while IFS= read -r line || [ -n "$line" ]; do
            # Skip empty lines and comments
            if [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]]; then
              echo "$line" >> "$DEPLOY_TEMP_DIR/$PRESIGNED_OUTPUT_FILE"
              continue
            fi

            # Extract both package_name and package_s3_uri from the line
            if [[ "$line" =~ ^([a-zA-Z0-9_]+):[[:space:]]*s3://([^[:space:]]+) ]]; then
              PACKAGE_NAME="${BASH_REMATCH[1]}"
              PACKAGE_S3_URI="s3://${BASH_REMATCH[2]}"

              # Generate a pre-signed URL for the S3 URI
              echo "Generating pre-signed URL for $PACKAGE_NAME..."
              PRESIGNED_URL=$(aws s3 presign "$PACKAGE_S3_URI" --expires-in 43200 --region us-west-1)
              presigned_url_line="$PACKAGE_NAME: \"$PRESIGNED_URL\""

              # Append the processed line to the output file
              echo "$presigned_url_line" >> "$DEPLOY_TEMP_DIR/$PRESIGNED_OUTPUT_FILE"
            else
              echo "Skipping line for presigning (no S3 URI found):"
              echo "$line"
            fi
          done < "$OUTPUT_FILE"

          # Verify the presigned urls file
          if [ -f "$DEPLOY_TEMP_DIR/$PRESIGNED_OUTPUT_FILE" ]; then
            echo "Presigned URLs file created successfully at $DEPLOY_TEMP_DIR/$PRESIGNED_OUTPUT_FILE."
          else
            echo "Failed to create presigned artifacts_urls.yml file." >&2
            exit 1
          fi
      - name: Save presigned URLs file to artifact
        uses: actions/upload-artifact@v4
        with:
          name: presigned-artifacts-urls-${{ github.run_id }}
          path: "${{ env.DEPLOY_TEMP_DIR }}/${{ env.PRESIGNED_OUTPUT_FILE }}"
  start-runner:
    name: Start EC2 instance using allocator and run ansible playbook
    runs-on: ubuntu-latest
    needs:
      - setup-runner
      - package-urls
    strategy:
      fail-fast: false # all jobs will run even if one fails
      matrix:
        system: ${{ fromJson(needs.setup-runner.outputs.OS_LIST) }}
    steps:
      - name: Configure AWS credentials (assume role)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          role-session-name:
          aws-region: us-east-1
      - name: Checkout wazuh/wazuh-automation repository
        uses: actions/checkout@v4
        with:
          repository: wazuh/wazuh-automation
          ref: ${{ inputs.AUTOMATION_REFERENCE }}
          token: ${{ secrets.GH_CLONE_TOKEN }}
          path: wazuh-automation/
      - name: Install python and create virtual environment
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-venv
          python3 -m pip install --upgrade pip
          python3 -m venv venv
          source venv/bin/activate
      - name: Install and set allocator requirements
        run: |
          pip install -r wazuh-automation/deployability/deps/requirements.txt
          pip install ansible-core==2.16
          ansible-galaxy collection install community.general
          ansible-galaxy collection install community.docker
          mkdir -p ${{ env.ALLOCATOR_PATH }}
          mkdir -p ${{ env.DEPLOY_TEMP_DIR }}
      - name: Set COMPOSITE_NAME variable
        run: |
          case "${{ matrix.system }}" in
            "CentOS_7")
              SUBNAME="centos-7"
              ;;
            "CentOS_8")
              SUBNAME="centos-8"
              ;;
            "AmazonLinux_2")
              SUBNAME="amazon-2"
              ;;
            "Ubuntu_16")
              SUBNAME="ubuntu-16.04"
              ;;
            "Ubuntu_18")
              SUBNAME="ubuntu-18.04"
              ;;
            "Ubuntu_20")
              SUBNAME="ubuntu-20.04"
              ;;
            "Ubuntu_22")
              SUBNAME="ubuntu-22.04"
              ;;
            "RHEL7")
              SUBNAME="redhat-7"
              ;;
            "RHEL8")
              SUBNAME="redhat-8"
              ;;
            *)
              echo "Invalid SYSTEM selection" >&2
              exit 1
              ;;
          esac
          COMPOSITE_NAME="${COMPOSITE_NAME/SUBNAME/$SUBNAME}"
          echo "COMPOSITE_NAME=$COMPOSITE_NAME" >> $GITHUB_ENV
      - name: Allocate EC2 instance
        id: allocator_instance
        run: |
          python3 wazuh-automation/deployability/modules/allocation/main.py --action create --provider aws --size large --composite-name ${{ env.COMPOSITE_NAME }} --working-dir $ALLOCATOR_PATH \
            --track-output $ALLOCATOR_PATH/track.yml --inventory-output $ALLOCATOR_PATH/inventory.yml --instance-name gha_ansible_${{ matrix.system }}_${{ github.run_id }} \
            --label-team devops --label-termination-date 1d

          instance_id=$(grep '^identifier' $ALLOCATOR_PATH/track.yml | awk '{print $2}')
          private_ip=$(aws ec2 describe-instances \
            --instance-ids $instance_id \
            --query 'Reservations[*].Instances[*].PrivateIpAddress' \
            --output text)

          # Parse the new inventory format
          ansible_host=$(yq e '.all.hosts[].ansible_host' $ALLOCATOR_PATH/inventory.yml)
          ansible_port=$(yq e '.all.hosts[].ansible_port' $ALLOCATOR_PATH/inventory.yml)
          ansible_user=$(yq e '.all.hosts[].ansible_user' $ALLOCATOR_PATH/inventory.yml)
          ansible_ssh_private_key_file=$(yq e '.all.hosts[].ansible_ssh_private_key_file' $ALLOCATOR_PATH/inventory.yml)
          ansible_ssh_common_args=$(yq e '.all.hosts[].ansible_ssh_common_args' $ALLOCATOR_PATH/inventory.yml)

          echo "[all]" > $ALLOCATOR_PATH/inventory
          echo "aio ansible_host=$ansible_host private_ip=$private_ip ansible_user=$ansible_user" >> $ALLOCATOR_PATH/inventory
          echo "[all:vars]" >> $ALLOCATOR_PATH/inventory
          echo "ansible_port=$ansible_port" >> $ALLOCATOR_PATH/inventory
          echo "ansible_ssh_common_args='$ansible_ssh_common_args'" >> $ALLOCATOR_PATH/inventory
          echo "ansible_ssh_private_key_file=$ansible_ssh_private_key_file" >> $ALLOCATOR_PATH/inventory
      - name: Save ALLOCATOR_PATH directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allocator-instance-${{ matrix.system }}-${{ github.run_id }}
          path: ${{ env.ALLOCATOR_PATH }}
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: wazuh-ansible/
      - name: Download the presigned urls file artifact
        uses: actions/download-artifact@v4
        with:
          name: presigned-artifacts-urls-${{ github.run_id }}
          path: ${{ env.DEPLOY_TEMP_DIR }}
      - name: Copy the presigned urls file to Ansible roles variables path
        run: |
          # Copy the presigned URLs file to the Ansible roles variables path
          cp $DEPLOY_TEMP_DIR/${{ env.PRESIGNED_OUTPUT_FILE }} wazuh-ansible/roles/vars/artifacts_urls.yml
      - name: Ansible Playbook run Wazuh AIO Single instance
        run: |
          ansible-playbook wazuh-ansible/.github/playbooks/aio-wazuh.yml \
          -i $ALLOCATOR_PATH/inventory \
          -l all \
          ${{ needs.setup-runner.outputs.VERBOSITY }}
  stop-runner:
    name: Stop allocated EC2 instance
    needs:
        - setup-runner
        - start-runner
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # all jobs will run even if one fails
      matrix:
        system: ${{ fromJson(needs.setup-runner.outputs.OS_LIST) }}
    if: ${{ always() }} # required to stop the runner even if the error happened in the previous jobs
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          aws-region: us-east-1
      - name: Checkout wazuh/wazuh-automation repository
        uses: actions/checkout@v4
        with:
          repository: wazuh/wazuh-automation
          ref: ${{ inputs.AUTOMATION_REFERENCE }}
          token: ${{ secrets.GH_CLONE_TOKEN }}
          path: wazuh-automation/
      - name: Install python and create virtual environment
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-venv
          python3 -m pip install --upgrade pip
          python3 -m venv venv
          source venv/bin/activate
      - name: Install and set allocator requirements
        run: |
          pip install -r wazuh-automation/deployability/deps/requirements.txt
      - name: Download the allocator artifact
        uses: actions/download-artifact@v4
        with:
          name: allocator-instance-${{ matrix.system }}-${{ github.run_id }}
          path: ${{ env.ALLOCATOR_PATH }}
      - name: Delete allocated EC2 instance
        run: python3 wazuh-automation/deployability/modules/allocation/main.py --action delete --track-output $ALLOCATOR_PATH/track.yml
