FROM ansible/ansible

ARG source_branch=master

# Update aptitude
RUN apt-get update

# Clone the corresponding branch of wazuh-puppet
RUN git clone -b $source_branch https://github.com/wazuh/wazuh-ansible.git

RUN cd wazuh-ansible && chmod +x ./run_cluster_mode.sh && pipenv install

RUN apt-get -y install ssh && apt-get -y update



